// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  text_blog: dynamic(() => import("./TextBlog")),
};
